All games
Accult/darina-mentor pull request #4
Opened 2023-09-19 09:13 UTC by Accult

Here are all the previously created games that have been placed in classes and combined by the parent class

For task "Hints OOP"

2023-09-19 19:36 UTC, rdchvd requested changes
there are couple of things I want to see in other way but you did a great work!!

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +            print('You have used hint already')
it would be better for this part to be a separate function.

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +        definition = self.get_hint_from_api()
you are getting hint (sending request, loosing time on it) when user haven't even asked for this. 
python is terribly slow, so think about every action you do :(

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +        pass
I would like you to do the method `get_hint_from_api ` here to work with the inheritance and polymorphism.

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +    def __init__(self):
if there are no actions in __init__, there is no need to write it
but it's not a mistake, if u like it, u can leave it.

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +        self.ATTEMPTS = 5
set them as class attributes, it's more pythonc way (imho)

p.s. you can read about it [here](https://www.toptal.com/python/python-class-attributes-an-overly-thorough-guide)

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +        self.RANDOM_NUMBER = random.randint(self.MINIMUM_RANGE, self.MAXIMUM_RANGE)
random_number is not really constant, as you set it using function, so remove uppercase here, i think
(also, think what else non constants do you have written in uppercase and try to fix it)

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +class NumberGuessingGame(Game):
I want to have hints for all the games 😢

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +        super().__init__()
Why do you use super here? (and in other classes)

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +        print("4. Quit")
that's cool!!

2023-09-19 19:36 UTC, rdchvd commented on games.py
> +                    return definition
huge work with dicts and defaults here! cool!

2023-09-26 15:22 UTC, rdchvd commented on games.py
> +                return f"Congratulations, you guessed right :)"
remove f

2023-09-26 15:23 UTC, rdchvd commented on games.py
> +            elif user_option in ScissorsPaperRockGame.OPTIONS:
self

2023-09-26 15:23 UTC, rdchvd commented on games.py
> +        random_option = random.choice(ScissorsPaperRockGame.OPTIONS)
self

2023-09-26 15:24 UTC, rdchvd commented on games.py
> +    def get_winner(self, user_option, random_option):
this can be staticmethod

2023-09-26 15:25 UTC, rdchvd commented on games.py
> +        self.word = random.choice(HangManGame.WORD_LIST)
self

2023-09-26 15:25 UTC, rdchvd commented on games.py
> +        if response.status_code in range(200, 300):
same with response status

2023-09-26 15:28 UTC, rdchvd commented on games.py
> +                print('You have used hint already')
that's why I want you to make it a function - you reuse the functionality.

2023-09-26 15:29 UTC, rdchvd commented on games.py
> +        for attempt in range(HangManGame.NUMBER_OF_ATTEMPTS):
self

2023-09-30 10:20 UTC, rdchvd commented on games.py
> +                return users_letter
```suggestion
                return users_input
```

2023-09-30 10:20 UTC, rdchvd commented on games.py
> +                    continue
there is no need in the `else`/`continue`, since there is no other functionality except of `if-statement`

2023-09-30 10:21 UTC, rdchvd commented on .pre-commit-config.yaml
> +        args: ["--line-length=120"]
you set line-length 120 here, and 150 lower
set 120 everywhere
+ add ruff in pre-commit

2023-09-30 11:22 UTC, Accult commented
Fixed it :)

2023-10-01 08:32 UTC, merged